### Obtener Bienvenida
GET http://localhost:3000/api

### Obtener TODOs
GET http://localhost:3000/api/todos

### Obtener TODO por Id
GET http://localhost:3000/api/todos/66bcee95a405a0b1600d5b0


### Postear TODO
POST http://localhost:3000/api/todos HTTP/1.1
Content-Type: application/json

{
    "title": "Test todo app 4",
    "completed": false
}

### Eliminar TODO
DELETE http://localhost:3000/api/todos/66bcee95a405a0b1600d5b0c