@base_url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDgzMjczMDY0YzhhNTQ3NmQyNjQ4NCIsImxhc3RMb2dpbiI6IjIwMjQtMDktMTFUMTY6NTQ6MzcuMzkxWiIsImlhdCI6MTcyNjA3MzY3NywiZXhwIjoxNzI2MDc1NDc3fQ.7768rj4Fj9dF5c1dWz9iWa_guDyboJb9e0tKnGmVl1g

###? Obtener Bienvenida
GET {{base_url}}/

###? Obtener TODOs
GET {{base_url}}/todos
Authorization: Bearer {{token}}

###? Test para el título
GET {{base_url}}/todos?title=Prueba
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Estado
GET {{base_url}}/todos?status=Completed
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Prioridad
GET {{base_url}}/todos?priority=High
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Categoría
GET {{base_url}}/todos?category=Work
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Fecha de Vencimiento
GET {{base_url}}/todos?dueBefore=2025-09-01
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Etiquetas
GET {{base_url}}/todos?tags=urgent,home
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Recordatorio
GET {{base_url}}/todos?reminderBefore=2024-10-01
Authorization: Bearer {{token}}

###? Obtener TODOs Filtrados por Fecha de Creación
GET {{base_url}}/todos?createdAfter=2024-08-24&createdBefore=2024-09-01
Authorization: Bearer {{token}}

###? Obtener TODO por ID
GET {{base_url}}/todos/66d720450356fba43a3d612d
Authorization: Bearer {{token}}

###? Postear TODO
POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Prueba test nuevo",
    "description": "Prueba test test test test test.",
    "status": "Completed",     
    "completed": true,
    "priority": "Low",
    "category": "Work",
    "reminder": "2024-09-21T10:00:00Z",
    "dueDate": "2024-09-30T23:59:59Z",
    "tags": ["urgent", "home"]
}

###? Modificar campos TODOs
PATCH {{base_url}}/todos/66ddedfcf4fad5106824aa7a
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Prueba con userId 2",
    "description": "Prueba con userId 2.",
    "status": "Pending",
    "completed": true,
    "priority": "High",
    "category": "Work",
    "reminder": "2024-10-21T10:00:00Z",
    "dueDate": "2024-10-30T23:59:59Z",
    "tags": ["urgent", "home"]
}

###? Eliminar TODO
DELETE {{base_url}}/todos/66ddedfcf4fad5106824aa7a
Authorization: Bearer {{token}}
