###? Obtener Bienvenida
GET http://localhost:3000/api

###? Obtener TODOs
GET http://localhost:3000/api/todos

###? Obtener TODO por ID
GET http://localhost:3000/api/todos/66c30d5cc731edb789995433


###? Postear TODO
POST http://localhost:3000/api/todos HTTP/1.1
Content-Type: application/json

{
    "title": "Test TODO nuevo 10",
    "description": "This is a description for the test TODO item.",
    "status": "Pending",     
    "completed": false,
    "priority": "Medium",
    "category": "Work",
    "reminder": "2024-09-21T10:00:00Z",
    "dueDate": "2024-09-30T23:59:59Z",
    "tags": ["urgent", "home"]
}

###? Modificar campos TODOs
PATCH http://localhost:3000/api/todos/66c30e75289a5e6c1e05d9b3 HTTP/1.1
Content-Type: application/json

{
    "title": "Test error prueba 1",
    "description": "This is a description for the test TODO item.",
    "status": "Pending",
    "completed": false,
    "priority": "High",
    "category": "Work",
    "reminder": "2024-10-21T10:00:00Z",
    "dueDate": "2024-10-30T23:59:59Z",
    "tags": ["urgent", "home"]
}


###? Eliminar TODO
DELETE http://localhost:3000/api/todos/66c30d5cc731edb789995433

