###? Obtener Bienvenida
GET http://localhost:3000/

###? Obtener TODOs
GET http://localhost:3000/todos

###? Obtener TODOs Filtrados por Estado
GET http://localhost:3000/todos?status=Completed

###? Obtener TODOs Filtrados por Prioridad
GET http://localhost:3000/todos?priority=High

###? Obtener TODOs Filtrados por Categoría
GET http://localhost:3000/todos?category=Work

###? Obtener TODOs Filtrados por Fecha de Vencimiento
GET http://localhost:3000/todos?dueBefore=2025-09-01

###? Obtener TODOs Filtrados por Etiquetas
GET http://localhost:3000/todos?tags=urgent,home

###? Obtener TODOs Filtrados por Recordatorio
GET http://localhost:3000/todos?reminderBefore=2024-10-01

###? Obtener TODOs Filtrados por Fecha de Creación
GET http://localhost:3000/todos?createdAfter=2024-08-24&createdBefore=2024-09-01

###? Obtener TODO por ID
GET http://localhost:3000/todos/66c5cdcf74fca3f046fae18a

###? Postear TODO
POST http://localhost:3000/todos HTTP/1.1
Content-Type: application/json

{
    "title": "Test Nuevo Todo 13",
    "description": "Descripcion del todo blablabla.",
    "status": "Completed",     
    "completed": true,
    "priority": "Low",
    "category": "Work",
    "reminder": "2024-09-21T10:00:00Z",
    "dueDate": "2024-09-30T23:59:59Z",
    "tags": ["urgent", "home"]
}

###? Modificar campos TODOs
PATCH http://localhost:3000/todos/66c30e75289a5e6c1e05d9b3 HTTP/1.1
Content-Type: application/json

{
    "title": "Test error prueba 1.2",
    "description": "Descripcion 2.1 del todo blablabla.",
    "status": "Pending",
    "completed": true,
    "priority": "High",
    "category": "Work",
    "reminder": "2024-10-21T10:00:00Z",
    "dueDate": "2024-10-30T23:59:59Z",
    "tags": ["urgent", "home"]
}

###? Eliminar TODO
DELETE http://localhost:3000/todos/66c5cdcf74fca3f046fae18a

