@base_url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDgzMjczMDY0YzhhNTQ3NmQyNjQ4NCIsImxhc3RMb2dpbiI6IjIwMjQtMDktMTJUMTg6MjM6NDUuODI1WiIsImlhdCI6MTcyNjE2NTQyNSwiZXhwIjoxNzI2MTY3MjI1fQ.n5gdc8L9YjsI8fEjcG982pUpQUKVyR126NbhWhEPuYk

###? Registrar Usuario
POST {{base_url}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "nickname": "exampleNick2",
    "firstName": "John2",
    "email": "johndoe2@example.com",
    "password": "securePassword123"
}

###? Validar email
GET {{base_url}}/auth/verify-email/ HTTP/1.1
Content-Type: application/json 

###? Iniciar Sesión
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "securePassword123"
}

###? Cerrar sesión
POST {{base_url}}/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###? Obtener Información de Usuario Logueado
GET {{base_url}}/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###? He olvidado mi contraseña
POST {{base_url}}/auth/forgot-password HTTP/1.1
Content-Type: application/json

{
    "email": "rpbertofernandezsepulveda@gmail.com"
}

###? Resetear la contraseña
PATCH  {{base_url}}/auth/forgot-password/   {user_token} HTTP/1.1
Content-Type: application/json

###? Cambiar contraseña
PATCH  {{base_url}}/auth/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currentPassword" : "securePassword123",
    "newPassword" : "securePassword123"
}